### ISSUE TITLE
More on "Domain does not exist"

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#107]
For domains that do exists, where the parent has NS records for the domain - but the child servers give SERVFAIL, Zonemaster should not say "Domain does not exist" - it is a CRITICAL error for the domain and should be displayed as such.

The CLI says this which is more verbose:

Seconds Level     Message
======= ========= =======
   0.95 ERROR     Nameserver ns1.example.com/123.123.123.123 did not return NS records. RCODE was NOERROR.
   0.96 ERROR     Nameserver ns2.example.com/123.123.123.123 did not return NS records. RCODE was NOERROR.
   0.99 CRITICAL  Not enough data about example.com was found to be able to run tests.

**Comment by sandoche2k** [comment]
@mtoma can you have a look at ths?

**Comment by mtoma** [comment]
This is way too complex to be caught by the simple preflight test. If we need this level of analysis before deciding if a domain is valid or not I agree with Calle's suggestion to use Zonemaster to determine if a domain can be tested or not.

**Comment by cdybedahl** [comment]
Should be fixed with dotse/zonemaster-backend@91cc586e4e5a66c421b15090167ad920f23f4d81.
