### ISSUE TITLE
Input field not visible on GUI (MAC/Chrome Version 42.0.2311.152 (64-bit))

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#108]
![image](https://cloud.githubusercontent.com/assets/5484470/7751508/b695b7a4-ffda-11e4-8985-d6fd29baa224.png)

**Comment by sandoche2k** [comment]
It works now

**Comment by pawal** [comment]
Not to reopen the issue, but if it happens again you should also post the javascript console log.

**Comment by sandoche2k** [comment]
Netxt time it happens for me, i will do that.
