### ISSUE TITLE
When using Apache as a frontend server and starman as a proxy backend the IP addresse is not available and thus not displayed correctly

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-gui#109]

**Comment by cdybedahl** [comment]
Assuming that you're using mod_proxy, the original IP address and hostname the client requested are available as the X-Forwarded-For and X-Forwarded-Host HTTP headers. See http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers
