### ISSUE TITLE
Non-existing test link generates Internal Server Error

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-gui#111]
...it should probably say something more in the line of "test not found" or something like that.

For example: "http://zonemaster.net/test/123456789".

**Comment by pawal** [comment]
Even though there is an error such as 500, a 404 such as this displays the same kind of page:
http://zonemaster.net/foo/1239

We should probably have a custom page for this, rather than using the Dancer default HTML exposing unnecessary info on our framework.

**Comment by pamasse** [comment]
If you try a bad test_id, the new GUI display an empty result table and an red alert display a message "No data for this test".

**Comment by sandoche2k** [comment]
Verified that this issue is solved in the new GUI
