### ISSUE TITLE
FAQ link missing

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#128]
FAQ link missing in the GUI

**Comment by mtoma** [comment]
Can I have more explanations on this issue?
Where is the missing link?
(http://zonemaster.re:5080)

**Comment by sandoche2k** [comment]
When you press on the menu FAQ in zonemaster.net

**Comment by mtoma** [comment]
Isn't is fixed on the pre-production environment?

**Comment by sandoche2k** [comment]
The issue concerned is the production environment (zonemaster.net)

**Comment by sandoche2k** [comment]
The current version has the FAQ
