### ISSUE TITLE
Rewrite the interface in Angular2

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-gui#150]
Angular1 is being deprecated and Angular2 will have its first release.
The interface should be rewritten in Angular2 for future maintainability.

**Comment by pawal** [comment]
Given that Angular 2 has not even been released yet, it will be at least couple of years until version 1.x is being deprecated.

**Comment by mtoma** [comment]
Drop the perl backend completly

**Comment by matsduf** [comment]
It does not look like Angular 1 is deprecated. I think we should structure Zonemaster before we create a new Zonemaster-gui.

**Comment by mtoma** [comment]
It is not. But solving any new issue using Angular1 is a pure loss of time as it will have to be rewritten at some point thus this issue is a prerequisite to about any user interface issues to the gui.

**Comment by sandoche2k** [comment]
@pamasse could be closed when the new GUI is integrated

**Comment by pamasse** [comment]
New GUI in Angular 5 (but Angular 6 will be soon available)
