### ISSUE TITLE
The non-Javascript interface tries to pull the CSS from localhost...

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster-gui#152]
In the source of `https://zonemaster.net/nojs`, we find:

```
        <link rel="stylesheet" href="http://localhost:81/css/nojs_style.css" />
```

**Comment by pamasse** [comment]
@bortzmeyer Nice to see you ! 
It's fixed in the new interface which is only in JS (but mobile compliant). If you want something else check the CLI.

**Comment by sandoche2k** [comment]
closed since the new interface does not have the non Js version
