### ISSUE TITLE
"perl Makefile.PL" returns warnings on missing files

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-gui#160]
$ perl Makefile.PL 
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	docs/installation-instructions.md
	docs/zonemaster-frontend-installation-instructions.md
	MYMETA.json
	MYMETA.yml
	README
Please inform the author.
Writing Makefile for Zonemaster_Dancer
Writing MYMETA.yml and MYMETA.json

Two files are created (MYMETA.json and MYMETA.yml) but the other three are still missing.

**Comment by mtoma** [comment]
Hi Mats,

This will be fixed with the release of the GUI to CPAN.
(Issue created on github.)

Michal

----- Original Message -----

**Comment by mattias-p** [comment]
I'm still getting this:
```
$ git checkout -f master && git clean -Xf && perl Makefile.PL
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Removing MYMETA.json
Removing MYMETA.yml
Removing Makefile
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        MYMETA.json
        MYMETA.yml
        README
Please inform the author.
Warning: prerequisite Dancer 1.3095 not found.
Warning: prerequisite Template 0 not found.
Warning: prerequisite Text::Markdown 0 not found.
Writing Makefile for Zonemaster_Dancer
Writing MYMETA.yml and MYMETA.json
```

**Comment by sandoche2k** [comment]
check with cpan -i again whether the components are installed

**Comment by mtoma** [comment]
Try again now Mattias

**Comment by mattias-p** [comment]
@mtoma The complaint about README is gone now. The MYMETA complaints are still there, as well as the suggestion to inform the author.

Aren't those files supposed to be missing from the kit? They're being generated anyway. Should they be included in some ignore-file?

**Comment by mtoma** [comment]
@mattias-p  Are you sure you checked out the latest version?
I did add them to MANIFEST.SKIP

Here is what I'm getting:


@mattias-p  Are you sure you checked out the latest version?
I did add them to MANIFEST.SKIP

Here is what I'm getting:
rm MYMETA.* && make manifest && perl Makefile.PL 
Warning: prerequisite Dancer 1.3095 not found.
Warning: prerequisite Template 0 not found.
Warning: prerequisite Text::Markdown 0 not found.
Warning: prerequisite YAML 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Zonemaster_Dancer
Writing MYMETA.yml and MYMETA.json

**Comment by mattias-p** [comment]
@mtoma I'm checking 59e9739. Our commands are working under different assumptions. Mine is ensuring a completely clean working directory while yours is assuming a working directory with a Makefile. That accounts for our difference in outputs.

I believe the MYMETA files should be removed from the MANIFEST file. Read the "MANIFEST" and "MYMETA.json and MYMETA.yaml" sections in http://neilb.org/2015/10/18/spotters-guide.html and see if you come to the same conclusion.

**Comment by mtoma** [comment]
Id did remove them from the MANIFEST file by adding them to MANIFEST.SKIP.
The regenerated MANIFEST is now committed as well. Hope it will solve the issue now.

**Comment by mattias-p** [comment]
@mtoma Sweet. `perl Makefile.PL` has stopped nagging about contacting the author.
