### ISSUE TITLE
FAQ doesn't work when browsers preffered language is not en/fr/sv

### ISSUE THREAD

**Issue by helb** [dotse/zonemaster-gui#184]
When visiting the web interface with a browser set to prefer a language not supported by *zonemaster-gui*, the FAQ page just stays empty:

![kookaburra_20170630_161027](https://user-images.githubusercontent.com/178133/27739384-ab71c550-5dae-11e7-8dd5-bfa5f99f4ad6.png)

Tested on *zonemaster.net* & *zonemaster.se* with:
- Firefox 54, `Accept-Language: cs,en-US;q=0.7,en;q=0.3`
- Chrome 61, `Accept-Language: cs,en-US;q=0.8,en;q=0.6`

I guess the best (and probably easiest) solution would be just to fall back to English here, like the other translations (menu, form labels) do…

**Comment by matsduf** [comment]
I think it is a good proposal to have "en" as default language.
