### ISSUE TITLE
The first click in FAQ doesn't work

### ISSUE THREAD

**Issue by helb** [dotse/zonemaster-gui#186]
The first click on the FAQ chapter link does not jump to the corresponding chapter, because it drops the `#` from URL – it goes to `/q2` instead of `/#q2` for example.

Subsequent clicks work normally (but the URL stays like `/q2#q3`).

![zonemaster-1](https://user-images.githubusercontent.com/178133/27742787-2da36c12-5dba-11e7-97ec-39160773b499.gif)

No idea about the cause. I think maybe Angular routing is messing with the anchors somehow – there are quite a few hits on *"angular broken anchor links"* google query.

**Comment by sandoche2k** [comment]
@pamasse fixed in the GUI ?
