### ISSUE TITLE
For the new GUI : Not able to click on info/notice/warning/error

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#227]
Like the option provided by CZ NIC, it will useful to click on the different tabs such as (Info, warning etc..)and go directly to those messages.

**Comment by pamasse** [comment]
In the "show" menu of the result area, the "tabs" are used to filter results. For example, if you click on error, you will only display the error messages.
So, if it's not enough clear, or not the good behaviour, could you explain your expectation ?

**Comment by sandoche2k** [comment]
When the mouse is hovered over the tabs, the user should know it is clickable.

**Comment by pamasse** [comment]
Done
