### ISSUE TITLE
Inconsistent/missing input validation for input parameters

### ISSUE THREAD

**Issue by lwid** [dotse/zonemaster-gui#28]
When using the Zonemaster service I accidentally stumbled upon an inconsistency in the progress callback. Out of curiosity I quickly had a look at the source code and found a potential SQL injection attack in the service (this has not been verified, hence _potential_). Details are as follows:

The following request is valid and returns proper JSON:
http://zonemaster.net/progress?id=871

The following request is invalid, should probably return JSON but returns "500 Internal Server Error":
http://zonemaster.net/progress?id=871A ==> 500 Internal Server Error

The following request is invalid but returns the same JSON as the first (and proper) request above:
http://zonemaster.net/progress?id=871;A

The discrepancy between the latter two responses indicate a broken input validation. Since neither "871A" nor "871;A" is a numerical ID the response should be identical for these two cases. Such a difference hints the possibility of a SQL injection.

I have no surveyed this any further but I had a quick look in the source code and it seems that at least the MySQL backend IS vulnerable. There is updating code such as:
  $self->dbh->do("UPDATE test_results SET progress=$progress WHERE id=$test_id") if ($progress);

Such code is a clear anti-pattern. Based on Defence In Depth (https://www.owasp.org/index.php/Defense_in_depth) action should be taken to mitigate this risk in both Frontend (using input validation, i.e. verifying that numerical id parameters are numerical - https://www.owasp.org/index.php/Input_Validation) as well as backend (using Prepared statements rather than string concatenations - https://www.owasp.org/index.php/Query_Parameterization_Cheat_Sheet).

By verifying input early in the chain bad requests can be rejected before even entering core components, and by using proper query parameterization the database should be safe even if a malicious user manages to submit bad input without being caught by the validation layer.

**Comment by mtoma** [comment]
It seems the semicolon gets filtered somewhere in the different layers of parameter parsing.
You can try it with a comma and you'll get a Server Error 500 as for the 871A parameter.

As for the security issue. The line you point at in the MySQL backed is vulnerable to SQL injection and will be fixed.

But one important thing to know about the current Frontend/Backend is that it supports 4 different database types: PostgreSQL, MySQL, CouchDB and SQLite.
Only the PostgreSQL backend can be considered production ready and secure as it is the only one that was audited by an external security consultancy company.
So it is very important to be aware that even with this piece of code fixed the MySQL backend can't be considered as production ready and secure for open use on the Internet.

Only the PostgreSQL backend is.

**Comment by mtoma** [comment]
This is a Backend issue and will be fixed in dotse/zonemaster-backend@25
