### ISSUE TITLE
Undelegated (pre-delegated) test looks for DS at parent

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-gui#29]
When doing an undelegated (pre-delegated) test, zonemaster (at zonemaster.net) reports back that it cannot find the DS record at a root server. That is the only comment under DNSSEC. I have tested a signed zone. I submitted the DS hash in the form.

**Comment by pawal** [comment]
Can we close this @cdybedahl?

**Comment by cdybedahl** [comment]
It's fixed in engine version 1.0.1. I don't know if the web GUI runs that version or not.

**Comment by pawal** [comment]
Ok, we keep this issue until @mtoma confirms that the GUI runs a new version of the engine.

**Comment by mtoma** [comment]
I need a domain and expected results to test this issue.

**Comment by pawal** [comment]
Here is an example:

expo$~>zonemaster-cli --ds 18937,5,1,10DD1EFDC7841ABFDF630C8BB37153724D70830A --ns ns1.loopia.se/93.188.0.20 --ns ns2.loopia.se/93.188.0.21 loopia.se
Seconds Level     Message
======= ========= =======
[...]
   3.77 ERROR     No DS record had a DNSKEY with a matching keytag.
   3.80 ERROR     Delegation from parent to child is not properly signed (no_dnskey).
[...]

The DS RR in this example is not matching any DNSKEY RR in the zone - and loopia.se does not have a DS properly published in the parent zone on the live DNS hierarchy.

**Comment by pawal** [comment]
The Zonemaster CLI needs keytag,algorithm,type,digest to perform validation on the DS to DNSKEY match - and the same seems to be true for the engine. @cdybedahl - is it necessary to have the keytag to perform this validation, and part of the call to the function? Can it be removed or made optional?

**Comment by cdybedahl** [comment]
The values asked for are the four RDATA fields in a DS record. Although I see that RFC4034 says that it's only intended to reduce the search space for a matching DNSKEY, so I suppose it could be made optional and set to a fixed value if not provided.

**Comment by pawal** [comment]
This issue needs an update in the engine, in the backend and the GUI. Should I create new issues for each change?

**Comment by sandoche2k** [comment]
@pawal pls. move this for release .3

**Comment by cdybedahl** [comment]
Looking at this case, it seems to consist of or raise some sub-cases.

1) Change the Engine API to allow adding fake DS records without specifying a key tag. In this case, the engine should use a random 16-bit integer value as the key tag.

2) The specification for test case dnssec02 is (I think) faulty, it should not require the key tag of the DS to match that of any DNSKEY. Only the cryptographic hash should matter.

3) The test implementation of dnssec02 should be modified to match the updated specification

4) The components using fake DS records may need to be adapted to the modified API. At a first guess, this includes all of the CLI, web GUI and web backend.

Do I understand things correctly? If so, it would be best to create separate issues for all these items, except that web GUI and backend can share one.

**Comment by pawal** [comment]
If I remember our discussions correctly, yes, this is the way we proposed it.

I really wish that Github could create dependencies between the issues. As for now, I could create the issue for step 1 here.

**Comment by cdybedahl** [comment]
Steps one and two are independent, so you could create those at the same time. Step one is fairly useless without step three, since it will only have one chance in 2^16 to pick the right key tag, but it doesn't hurt to have it implemented.

**Comment by pawal** [comment]
See #62.
