### ISSUE TITLE
Using the back (and forward) button is broken

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#32]
_From @joelpurra on December 11, 2014 15:39_

When clicking links in the menu (for example FAQ), the browser's address bar is not updated. Because it's not updated, clicking the back button means leaving the zonemaster.net website. This is unexpected behavior.

_Copied from original issue: dotse/zonemaster#283_

**Comment by sandoche2k** [comment]
@pawal for release .4

**Comment by pamasse** [comment]
Fixed with the new GUI

**Comment by sandoche2k** [comment]
Fixed.
