### ISSUE TITLE
HTTPS does not work for zonemaster.net

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#37]
_From @jschlyter on December 11, 2014 13:28_

Subject says it all. It's almost 2015, HTTPS everywhere.

_Copied from original issue: dotse/zonemaster#277_

**Comment by pawal** [comment]
Yes please. @mtoma, is this something you can fix?

**Comment by pawal** [comment]
_From @mtoma on December 11, 2014 13:38_

I'm looking into it right now.

----- Original Message -----

**Comment by pawal** [comment]
_From @mtoma on December 11, 2014 14:45_

There are a few possible ways to go here.
If we want "just" https I can create a self-signed certificate.

If we want a real certificate there are a few things to consider:
- Who will be in charge of the creation of the certificate?
- How are we planning to redirect the other zonematser.TLD domains? (as now it could be pretty easy  to add another domain to point to the same IP, it will be more complicated if we use a certificate per domain)

**Comment by pawal** [comment]
_From @jschlyter on December 11, 2014 15:4_

Just buy a normal webtrust cert for zonemaster.net and be done with it? USD 10.

**Comment by pawal** [comment]
I agree with @jschlyter, a normal domain validated cert is fine.

For your two other questions, who will be in charge for creating and renewing the cert is the party responsible for running the web site right now. Redirects is not a related issue, any redirects will be done to zonemaster.net that will use the correct certificate. If other content is added to the other zonemaster.TLD sites, those also need certificates. It is not complicated. But I recommend that you use the HSTS header for zonemaster.net.

**Comment by pawal** [comment]
_From @amelsec on December 11, 2014 20:18_

+1. 

 

Från: Patrik Wallström [mailto:notifications@github.com] 
Skickat: den 11 december 2014 21:16
Till: dotse/zonemaster
Ämne: Re: [zonemaster] HTTPS does not work for zonemaster.net (#277)

 

I agree with @jschlyter <https://github.com/jschlyter> , a normal domain validated cert is fine.

For your two other questions, who will be in charge for creating and renewing the cert is the party responsible for running the web site right now. Redirects is not a related issue, any redirects will be done to zonemaster.net that will use the correct certificate. If other content is added to the other zonemaster.TLD sites, those also need certificates. It is not complicated. But I recommend that you use the HSTS header for zonemaster.net.

**Comment by pawal** [comment]
What is the status on this @mtoma?

**Comment by amelsec** [comment]
I really urge you to fix https on zonemaster asap. It is embarrasing to promote zonemaster while I am promoting https everywhere during my presentations. I ALWAYS get that comment "You tell us to use https everywhere, but zonemaster doesn't, why?" It was noticed in december. Now we have April. It is not that difficult. I would really want to get an update of where we stand on this, and a time when it will be solved. Thank you. @mtoma

**Comment by sandoche2k** [comment]
@pawal for release .2

**Comment by pawal** [comment]
This hopefully should not require a code change, and thus not being targeted for any release.

We have been waiting 6 months for this now.

**Comment by sandoche2k** [comment]
Michal has already initiated the issue with our IT dept.

We hope to get this done ASAP.

**Comment by sandoche2k** [comment]
@mtoma could be closed?

**Comment by mtoma** [comment]
The new certificate with the zonemaster.net domain is installed.

**Comment by jschlyter** [comment]
Redirect from http to https seems missing, as well as HSTS header.

**Comment by mtoma** [comment]
Can you check it now please? @jschlyter

**Comment by jschlyter** [comment]
Good!
