### ISSUE TITLE
Appearance in different browsers

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#39]
_From @sandoche2k on November 18, 2014 15:23_

@Michal/Web Front-end/Post1.0

http://browsershots.org/http://192.134.4.83/

_Copied from original issue: dotse/zonemaster#233_

**Comment by pawal** [comment]
_From @mtoma on November 18, 2014 15:40_

The vast majority of the browser screen-shots differences are probably caused by the fact that the service does not wait long enough for the java-script to complete rendering the web page.

----- Original Message -----

**Comment by pawal** [comment]
Is that really correct? I would also suspect javascript incompatibilities as a cause for a blank page.

**Comment by pawal** [comment]
_From @mtoma on November 18, 2014 17:48_

That could be the case if the white screen-shots started at a certain version of the same browser because of some unsupported feature.
In the screen-shots this is not the case. It shows Firefox 11 as showing the interface correctly and in Firefox 31 it shows as blank screen.
In addition I'm using Firefox 25 on my Linux box and I never saw any problem. 

----- Original Message -----

**Comment by pawal** [comment]
FWIW, this is the result on dnscheck.iis.se:
http://browsershots.org/http://dnscheck.iis.se/

**Comment by pawal** [comment]
_From @mtoma on November 20, 2014 8:29_

dnscheck.iise.se does not use any javascript rendered content on the start page. In the Zonemaster GUI ALL the content is Javascript rendered.
I can look at this without problems if anyone is able reproduce the blank page problem with one of the (main) browsers showing a blank page for the Zonemaster GUI.

----- Original Message -----

**Comment by pawal** [comment]
_From @sandoche2k on November 26, 2014 15:32_

Move it to post 1.0

**Comment by pawal** [comment]
_From @sandoche2k on December 8, 2014 13:47_

Windows 7,8 - browser IE 8,9,10

**Comment by pawal** [comment]
I have a new test started here:
http://browsershots.org/http://zonemaster.net/

Worth looking at again...

**Comment by pawal** [comment]
We will watch this on case by case basis.

**Comment by sandoche2k** [comment]
@pawal assignee @mtoma and for release .4

**Comment by pamasse** [comment]
Still relevant for the new GUI ?

**Comment by sandoche2k** [comment]
This is not a priority. I will just keep it for validation once the new GUI is tested.

**Comment by sandoche2k** [comment]
Can be closed.
