### ISSUE TITLE
Web site optimization

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#40]
_From @pawal on November 18, 2014 14:32_

There are many services that can measure the loading speed of a website and helps to suggest improvements. There are a number of things that can be improved in the Web GUI from this report:

http://gtmetrix.com/reports/192.134.4.83/L1dIzf1m

Recommendations top 5:
- Enable gzip compression
- Leverage browser caching
- Specify a Vary: Accept-Encoding header
- Minify JavaScript
- Defer parsing of JavaScript

_Copied from original issue: dotse/zonemaster#232_

**Comment by sandoche2k** [comment]
@pawal - pls. move it to .4

**Comment by pamasse** [comment]
Done by angular 5 (Leverage browser caching, Minify JavaScript, Defer parsing of JavaScript).
"Specify a Vary: Accept-Encoding header" => We should incorporate this recommendation in the installation doc (with the example of virtualhost).
https://kinsta.com/knowledgebase/specify-vary-accept-encoding-header/

"Enable gzip compression"  => Apache or nginx (or other web server) configuration
