### ISSUE TITLE
Results are not translated in the language chosen in the index

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#41]
_From @sandoche2k on November 17, 2014 10:45_

[Requirement] 
When a user has chosen a language the index, faq and results MUST be in
the chosen language UNLESS specific messages are missing where in such a case
the default language COULD be used for these, or all, messages.

Test: 
1. afnic.fr (Chosen lang "en")
2. Choose other language such as "fr" or "sw", the results are still in English

_Copied from original issue: dotse/zonemaster#220_

**Comment by pawal** [comment]
_From @mtoma on November 17, 2014 10:48_

All interface are translated on the fly.
Results are NOT.
To have results translated first chose a language than get some results.

----- Original Message -----

**Comment by pawal** [comment]
_From @sandoche2k on November 17, 2014 11:4_

Yes, this is how it works now.

But I understood the requirement (that comes from GUI Combined
requirements), that i have added in the comment works like in "dnscheck",
where you change the language after running the tests and the results are
in the language chosen.

**Comment by pawal** [comment]
_From @sandoche2k on November 18, 2014 15:43_

I think this can be moved to post 1.0

**Comment by sandoche2k** [comment]
@pawal - pls. move it to release .4

**Comment by sandoche2k** [comment]
works in the new GUI. Hence close this issue
