### ISSUE TITLE
Add policy and test profiles for the Web GUI

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#42]
_From @pawal on November 6, 2014 15:10_

We might need to add other policies and test profiles in addition to the defaults to the GUI, based on other use cases of DNS. See ticket #167.

_Copied from original issue: dotse/zonemaster#175_

**Comment by pawal** [comment]
This is a dependency on the issue https://github.com/dotse/zonemaster-engine/issues/19 in the test engine.

**Comment by pawal** [comment]
Stalled, waiting for https://github.com/dotse/zonemaster/issues/324

**Comment by sandoche2k** [comment]
@pawal - pls. move it to release .3
