### ISSUE TITLE
Direct link to test a domain

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#44]
_From @joelpurra on December 11, 2014 15:43_

Is there a way to create a direct link to *test* a domain? This way I can share the most recent results instead of a fixed point in time.

Suggestion:
http://zonemaster.net/test/joelpurra.com

_Copied from original issue: dotse/zonemaster#285_

**Comment by pawal** [comment]
I am not sure this is a good idea. All kind of misbehaving (not respecting robots.txt) client will initiate tests.

**Comment by pawal** [comment]
_From @mtoma on December 12, 2014 8:57_

Could you elaborate more on this particular use case? If you sent a link like http://zonemaster.net/test/joelpurra.com to someone you won't have any control on the point in time where this test will bu run. This more or less means that the results will not be very predictable.

**Comment by pawal** [comment]
_From @joelpurra on December 12, 2014 10:14_

@pawal: you're right, bots could hit links like that hard. Perhaps it could just show the most recent results then?

@mtoma: predictability isn't as important as the most recent results being shown in this case. The use case is that someone tells me that my domain is misconfigured - "here, look at the current values." I've had previous issues with links to older results showing domain errors (on another domain testing site) making users think they hadn't been fixed.

Considering the bots, showing the most recent results might be better. Links/actions such as "look at the most recent results for this domain," "re-run tests on this domain" would be a nice complement.

**Comment by pawal** [comment]
_From @cdybedahl on December 12, 2014 10:21_

A link that shows the most recent test for a domain would be kind of neat. Although it would probably upset the kind of person who thinks that Zonemaster is publishing secrets about their site (yes, we just had an email like that) even more.

**Comment by mtoma** [comment]
To do this kind of testing a public API seems to be more suitable.
The project already has a JSON-RPC API in the backend module.
Would you be interrested if we bade this API public?
This would allow easy softwer driven or automated testing of domains.
