### ISSUE TITLE
export the result in HTML format

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#46]
_From @sandoche2k on October 23, 2014 8:48_

_Copied from original issue: dotse/zonemaster#130_

**Comment by pawal** [comment]
_From @mtoma on October 23, 2014 14:1_

Is this really needed?

**Comment by pawal** [comment]
_From @sandoche2k on October 23, 2014 18:58_

This is part of the requirements.

**Comment by pawal** [comment]
_From @mtoma on October 24, 2014 7:3_

Yes ok. But I don't know what this requirement means. You can export as HTML already now with a simple "save page as" in your browser.
If this is not enough I need to know what kind of HTML formatting is required.

----- Original Message -----

**Comment by pawal** [comment]
_From @einar on October 24, 2014 8:56_

Although the req comes from you (AFNIC via ZoneCheck) I see that option as a very minimalistic HTML-export-function; perhaps for the option of viewing a result on a Kindle or similar device with an experimental web browser. So, if I could chose the formatting, I would go for the lowest possible "style" and maximum "interop", not at all what you would get with "save page as"... ;)

**Comment by pawal** [comment]
_From @mtoma on October 24, 2014 9:0_

The kind of output the NonJS interface offers for example?

----- Original Message -----

**Comment by pawal** [comment]
Was not the original suggestion to have an output that is printable as a report, and that could be saved as HTML or printed (as a PDF or whatever).

**Comment by pawal** [comment]
_From @mtoma on October 24, 2014 9:14_

Ok, I see so more like the results from the "advanced results" tab but all on one single HTML page to allow easy save or print of the report, right?

----- Original Message -----

**Comment by pawal** [comment]
I am not sure on how to present the report in the best way for the user. Perhaps also add a short summary on the top with any warnings/errors, or "OK"?

**Comment by pawal** [comment]
_From @sandoche2k on October 24, 2014 9:48_

I think we can move this issue for the beta release.

**Comment by sandoche2k** [comment]
@pawal move to priority high (5th position in the survey)

**Comment by sandoche2k** [comment]
@pawal - pls. move it to release .3

**Comment by sandoche2k** [comment]
@mtoma  Click on “Export” the content that we see in “Advanced section” will be displayed in separate web page
