### ISSUE TITLE
Pagination for history of runs for the same domain

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#48]
_From @sandoche2k on October 23, 2014 8:46_

_Copied from original issue: dotse/zonemaster#128_

**Comment by pawal** [comment]
_From @mtoma on November 3, 2014 15:11_

This is rather heavy development and does not seem to me to be blocking until we have more than a thousand tests to show in the history for the same domain.
In my opinion this should be postponed until the web interface users really need it.

**Comment by pawal** [comment]
_From @sandoche2k on November 3, 2014 15:59_

I agree. Moved to release 1.0

**Comment by sandoche2k** [comment]
@pawal - pls. move it to release .4

**Comment by einar** [comment]
Hmm, well DNSCheck handles it well and currently (for example) IIS.SE has 2,820 tests accessible with the first ones logged in 2008. I cant see any reason why we should NOT have this, it should have been in 1.0 as a feature and requirement from DNSCheck. But move/postpone it anyways.

**Comment by sandoche2k** [comment]
could be closed with the new GUI @pamasse

**Comment by sandoche2k** [comment]
fixed
