### ISSUE TITLE
Interface does not work in IE

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#49]
Tested rediff.com, afnic.fr.

No results until 2 minutes. Hence stopped.

**Comment by mtoma** [comment]
Could you describe what "does not work in IE" means in some more details?
Did you test the interface in another browser and did it work?
What version of IE is that?
Can I have some screen captures?

**Comment by sandoche2k** [comment]
IE version : 11.0.9600.17501
OS : Windows 7
Screen capture (After 5 mins)

![image](https://cloud.githubusercontent.com/assets/5484470/5935206/848a31dc-a6d8-11e4-8f69-bab3882dcf81.png)

**Comment by sandoche2k** [comment]
Yes it works in Chrome in the same OS : Windows 7

**Comment by cdybedahl** [comment]
Just in case someone doesn't already know about it: Microsoft provides time-limited VM images with many combinations of Windows and IE versions specifically for the testing of web applications, at https://www.modern.ie/

**Comment by sandoche2k** [comment]
That was an useful pointer :-)

**Comment by pawal** [comment]
Erika claims that it is still not working on IE 9 on Windows 7.

**Comment by sandoche2k** [comment]
The filed for domain name input is not visible (From Erika) [IE 9 on Windows 7]

![image](https://cloud.githubusercontent.com/assets/5484470/6328167/bf12ac94-bb64-11e4-8862-ad55cb0423f0.png)

**Comment by mtoma** [comment]
Did you clear the browser cache by pressing CTRL+R?

**Comment by ErikaOlsson** [comment]
Yes, I have tried that. Stil not working

**Comment by mtoma** [comment]
Hello, Erika, can you give me a higher resolution screen capture including the address bar please?
I have a virtual machine with IE9 on Win7 and it works here.

**Comment by mtoma** [comment]
Could you also follow this tutorial to ensure zonemaster.net is not listed as a site for "IE's compatibility mode".
http://www.sevenforums.com/tutorials/1196-internet-explorer-compatibility-view-turn-off.html

**Comment by ErikaOlsson** [comment]
![ie zm](https://cloud.githubusercontent.com/assets/9248938/6330370/ee0bd0da-bb77-11e4-99e1-c53ab6b2ec0c.png)
I have tried again and also asked Einar to check it, still not working for me, please see attached.

**Comment by mtoma** [comment]
Ok, everything seems normal.
I'm unable to reproduce this here.
Could you please enable Script debugging for your browser?
In the English version it is:
Options (Shortcut ALT-X) -> Internet Options -> Advanced tab -> (Uncheck) Disable Script Debbuging (both checkboxes)
and reload the page with CTRL-R?

**Comment by ErikaOlsson** [comment]
Done that, still not working for me. Can someone else try?

**Comment by mtoma** [comment]
You should be able to see some kind of error messages in dialog boxes. Do you see something?
Can you also explicitly clear the browser history with Internet Options (ALT-X) -> General Tab -> Browsing History -> Check all Items -> Delete
