### ISSUE TITLE
Missing link in the Web site

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#56]
_From @bortzmeyer on February 3, 2015 15:48_

FAQ in French, the text says "Le lien suivant, par exemple, renvoie sur les résultats de la dernière analyse de "afnic.fr":" but there is no "lien suivant".

_Copied from original issue: dotse/zonemaster#332_

**Comment by sandoche2k** [comment]
@MTO could be closed

**Comment by pahi** [comment]
Close this ticket?

**Comment by bortzmeyer** [comment]
@pahl Of course not, the problem is still there.

**Comment by sandoche2k** [comment]
@pawal assignee @mtoma and for release .2

**Comment by sandoche2k** [comment]
@mtoma can you finish and close this
