### ISSUE TITLE
Enable DS records in the interface

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#62]
Enable DS records on the interface when the DS hash algorithm field has been added in the gui. This is a reference to #58.

**Comment by mtoma** [comment]
Shouldn't this issue be "Enable DS records on the interface"?

**Comment by pawal** [comment]
Yes, sorry about that.

**Comment by sandoche2k** [comment]
@pawal - pls. move it to release .3

**Comment by sandoche2k** [comment]
@mtoma 

Implement with four fields

**Comment by mtoma** [comment]
Could I have a full zonemaster command line example of a test with a DS record related options please?

**Comment by sandoche2k** [comment]
To obtain the DS 
dig +short DS grepular.com
30528 7 1 FB9A057A114268C19EE47A69417E63203A149F06

To run in the ZM CLI 

zonemaster-cli --ds 30528,7,1,FB9A057A114268C19EE47A69417E63203A149F06 grepular.com
Seconds Level     Message
======= ========= =======
   2.24 NOTICE    Nameserver snake.grepular.com has an IP address (87.81.168.104) with mismatched PTR result (5751a868.skybroadband.com.).
   4.84 WARNING   All nameservers have IPv6 addresses in the same AS (6939).
   5.95 NOTICE    SOA 'retry' value (900) is less than the recommended minimum (3600).

@pawal Am i right?

**Comment by mtoma** [comment]
Where whould we like to see dropdown lists?

----- Original Message -----

**Comment by sandoche2k** [comment]
Under "Digests" under the menu  "pre-delegated domain"

**Comment by mtoma** [comment]
Yes  of course.
My question as more about the algorithm and digest type fields.
After reading this: https://www.ietf.org/rfc/rfc4034.txt
It seems only one digest type is supported as of now.
Is there a real need to allow to select the digest type as (as of now) there is only one digest type supported (§A.2.  DNSSEC Digest Types of the rfc4034)?

**Comment by sandoche2k** [comment]
![image](https://cloud.githubusercontent.com/assets/5484470/11299877/b79f6768-8f8a-11e5-8ccc-30b1d3489a68.png)

**Comment by sandoche2k** [comment]
@mtoma above figure for an example. We need the digest type since the code needs it. And, i am not sure whether there is support for only one digest type as you can see from the above figure.

**Comment by mtoma** [comment]
Yes, strange, the RFC seems to state that there is only one supported but your screen capture offers two.
Ok then I'll code it with two dropdown lists one for the algorithm and one for the digest type as your screen capture shows it.

**Comment by mtoma** [comment]
Ok those two seem more up to date.
I'll base the devs on those:
http://www.iana.org/assignments/ds-rr-types/ds-rr-types.xhtml
http://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml

**Comment by pawal** [comment]
The best would be to ask the engine what it supports, to avoid double code for all algorithms. But for now use the IANA registry.

**Comment by mtoma** [comment]
Do we have some command line option that can be used to ask the engine to list the supported algorithms?

**Comment by pawal** [comment]
> On 20 Nov 2015, at 15:43, mtoma <notifications@github.com> wrote:
> 
> Do we have some command line option that can be used to ask the engine to list the supported algorithms?

There is no support at all to query the engine for what it implements. Good future idea though.
You can only export the policy and list test cases.

**Comment by mtoma** [comment]
Swedish translations needed:
,"Key Tag"								:"Identifiant"
,"Algorithm"								:"Algorithme"
,"Digest type"								:"Drapeaux"
,"Digest"									:"Clé publique"

**Comment by mtoma** [comment]
Closed with
https://github.com/dotse/zonemaster-gui/commit/f1870061fcf3a28e088408081eeda948f508c69d
