### ISSUE TITLE
Do we need a directory "Zonemaster_Dancer" ?

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#68]
Why not move all the contents in "Zonemaster_Dancer" directly under "Zonemaster_GUI" and remove the "Zonemaster_Dancer" directory.

Thus.. aligning the format of all other repositories.

**Comment by pawal** [comment]
I agree. And "Docs" should be lowercased to "docs", and README should be a markdown document called README.md.
