### ISSUE TITLE
Version change from 1.0.0 to 1.0.1 for release 2015.1

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-gui#78]

**Comment by sandoche2k** [comment]
Can you check and close the issue @mtoma

**Comment by sandoche2k** [comment]
@mtoma - HIGH PRIORITY - please update to current release ASAP

**Comment by pawal** [comment]
Version has already been changed to 1.0.2 and has been release in milestone 2015.1. See the Wiki page: https://github.com/dotse/zonemaster/wiki/Zonemaster-Distribution-Releases

**Comment by mtoma** [comment]
It is done. It needs to be put online on the server.

----- Original Message -----
