### ISSUE TITLE
Install new engine on the machine running zonemaster.net

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#80]
There has been a new release of the engine fixing a number of things. Please install version 1.0.2 on the machine running zonemaster.net.

https://github.com/dotse/zonemaster-engine/releases

Full changelog is here:
https://github.com/dotse/zonemaster-engine/blob/master/Changes

**Comment by mtoma** [comment]
Done

**Comment by mtoma** [comment]
The version displayed on the website is still 1.0.0 as it is hardcoded until we decide on the global subversion strategy.
Shoul I change this to something else? 1.0.1? 1.0.2? 2015-01?

**Comment by sandoche2k** [comment]
Can we have a change log for backend and GUI as here : https://github.com/dotse/zonemaster-engine/blob/master/Changes

For the versioning, you can add it as follows 1.0.2 DD Month YY.

**Comment by pawal** [comment]
Please use ISO 8601 of you plan to use date formats.

**Comment by sandoche2k** [comment]
Please check and close the issue @mtoma
