### ISSUE TITLE
That doesn't look right

### ISSUE THREAD

**Issue by cdybedahl** [dotse/zonemaster-gui#81]
Necronomicon-II:~% curl http://zonemaster.net/resolve\?data=www.google.com
 {"result":[{"www.google.com":"74.125.140.99"},{"www.google.com":"74.125.140.147"}, {"www.google.com":"74.125.140.104"},{"www.google.com":"74.125.140.106"},{"www.google.com":"74.125.140.105"},{"www.google.com":"74.125.140.103"},{"www.google.com":"2a00:1450:400c:c08:0:0:0:67"}]}                                                                                                                                                

 Necronomicon-II:~% curl http://zonemaster.net/resolve\?data=www.microsoft.com
 Internal Server Error                                                                                                                                                   
 Necronomicon-II:~%

**Comment by mtoma** [comment]
Is there a normal use-case for this somewhere/somehow?

**Comment by cdybedahl** [comment]
I stumbled on it while trying to figure out how the GUI works. Working fine for one name and crashing for another that has no obvious difference means that there is a problem _somewhere_ in the code. Unless you figure out where and what it is, you have no idea if it's going to happen during ordinary use or not. Also, the use for that service may well be extended at some point in the future.
