### ISSUE TITLE
Remove the contents of Zonemaster-Dancer and movie it to the parent Zonemaster-GUI directory

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#82]
As now we have zeroed on to a single GUI, do we need a specific directory "Zonemaster-Dancer"?

**Comment by mtoma** [comment]
We don't need it but if it is there it adds an information to the potential user.
Plus there is another frontend in the works, I'll demonstrate it next week. Not sure if this is something we want to put into github or not.

**Comment by cdybedahl** [comment]
> On 26 feb 2015, at 17:31, mtoma <notifications@github.com> wrote:
> 
> Plus there is another frontend in the works


When did we decide to write a new one? Is that decision something I missed because I couldn’t come to the meeting in Paris?

— 
Calle Dybedahl
calle.dybedahl@init.se

**Comment by mtoma** [comment]
No, it is not a decision. It is an optional suggestion, you didn't miss anything.
I wrote a small Twitter-Bot frontend for Zonemaster that will answer tweets sent to the @ZonemasterNet account with results of a Zonemaster test and a link to the detailed results on zonemaster.net.

It should be online today for testing purposes.

If we think this is something useful than we can keep it and add it to the zonemaster-gui project as another frontend. (I talked about it with our communications department and they were very enthusiastic about this idea).
If we decide it is not a good idea and that the project has time to spend on things like moving files from one directory to another. Then I'll remove the Zonemaster_Dancer directory.

----- Original Message -----

**Comment by sandoche2k** [comment]
Twitter-Bot is a good idea. Please add it to the wishlist.

Regarding the new Client GUI; i think we have to make the existing stable.
There should be only one interface as part of the zonemaster-gui component.

Regarding the directory modification, i think we have to follow certain
best practices. Previous experience suggests that the DNS community, which
is our main target audience, is very strict about these things.

**Comment by mtoma** [comment]
Hello Sandoche,

It seems I didn't make myself understand clearly.
The twitter bot is nearly finished, id did it during the DNSSEC training we had with Stephane. What is remaining will not be written in the Zonemaster time-sheets. I'll do it on my own spare time.

There is no other "new Client GUI" in works anywhere. The twitter bot IS the additional client GUI, that should be put in the zonemaster-gui project and kept in let say Zonemaster_twitter directory, what would in turn make the removal of Zonemaster_Dancer a very bad idea.

Is it clearer now?

Michal

----- Original Message -----

**Comment by pawal** [comment]
Please keep it in another personal repository until it has been adopted by the project.

However, even if it is adopted by the project, it should not be part of the GUI repository, unless it depends on it entirely. My guess is that it only depends on the backend - so it should probably be kept in another repository anyway.

**Comment by mtoma** [comment]
No worries, Patrik. I wont keep it in any repository until the decision is made by the project to adopt it.
It could be kept in another repository as well. But having one repository for one file of a few hundred lines of code seems a little over dimensioned for me.
My personal options is to keep everything that objectively is a GUI in the zonemaster-gui repository.

----- Original Message -----

**Comment by sandoche2k** [comment]
Thanks for the clarification.

Do you want it (twitter bot) to be added as part of the Survey
questionnaire?

Sandoche.

**Comment by mtoma** [comment]
Yes, that might be a good idea, yes.

----- Original Message -----
