### ISSUE TITLE
Maintainer documentation needed

### ISSUE THREAD

**Issue by cdybedahl** [dotse/zonemaster-gui#83]
The GUI really needs documentation describing what functionalities are implemented where and how. It's not obvious what functionality is implemented on the Perl side and what is in AngularJS code. In between the double layers of templating, the AJAX calls and the AngularJS directives, it's difficult to know how things fit together. Documentation describing the control flow and data manipulation would be very helpful.

**Comment by sandoche2k** [comment]
@pawal - assignee @mtoma and to release .2

**Comment by sandoche2k** [comment]
@mtoma - This is part of the release 2015.2. Can you have a look at this issue?

**Comment by sandoche2k** [comment]
Basic documentation to be done by @mtoma
Then, work with @mattias-p and @sandstrand  to complete this issue.

**Comment by pamasse** [comment]
New GUI upcoming with its documentation.

**Comment by pamasse** [comment]
Very simple documentation will be done in the Readme.
Since all is done in javascript (Angular 5), no need to describe any custom behavior.
