### ISSUE TITLE
Zonemaster-GUI shows errors for the zones that are not signed with DNSSEC

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#85]
http://zonemaster.net/test/5120

**Comment by bortzmeyer** [comment]
And three errors, while the cause is the same (no signature).

**Comment by sandoche2k** [comment]
@pawal assign it to @mtoma and for release .3

**Comment by sandoche2k** [comment]
@mtoma ?

**Comment by sandoche2k** [comment]
@mtoma Verified during the meeting. You can close this issue.
