### ISSUE TITLE
while testing gouv.fr the response is "Domain does not exist" which is not true

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-gui#86]
The response from the CLI is : 0.20 CRITICAL  Nameservers for "fr" provided no NS records for tested zone. RCODE given was NOERROR.
   0.21 CRITICAL  Not enough data about gouv.fr was found to be able to run tests.

From DNSCHECK "http://dnscheck.iis.se/?time=1418292987&id=4423656&view=basic&test=standard"
From DNSViz : http://dnsviz.net/d/gouv.fr/dnssec/
From ZC : http://www.afnic.fr/outils/zonecheck/zc.cgi?zone=gouv.fr&afnic=t&intro=t&testname=t&explain=t&progress=counter&report=byseverity&format=html&lang=fr&errorlvl=&chkmail=t&chkzone=t&chkrir=t&transp3=ipv4&transp3=ipv6&transp4=std

**Comment by bortzmeyer** [comment]
Seems to be a general problem with ENTs. For instance, testing e.0.1.0.a.2.ip6.arpa yields the same erroneous message.

**Comment by cdybedahl** [comment]
The messages are strictly correct. The test engine does not get any NS records for those names, so it doesn't have enough data to run any tests. What's not working here is the translation from that to human language. Perhaps we should add a "that's not a domain" message after all.

**Comment by bortzmeyer** [comment]
The raw messages are correct but the erroneous "domain does not exist" come from the Twitter gateway. https://twitter.com/ZonemasterNet/status/573054810565578752

**Comment by cdybedahl** [comment]
Ah. I don't know if @mtoma has set up anywhere to submit bug reports for that.

**Comment by mtoma** [comment]
There is no place to submit bugs for the Twitter Bot as it maps exactly to the behavior of the "Domain Check" tab of the GUI. The GUI does give exactly the same error message when testing gouv.fr and it is the result of the "preflight" test of the "Domain Check" tab. The preflight test fetches the NS records for the domain and does not find any and thus refuses to start the test. The message is not good of course as in this specific case the domain exists. If we want a more precise diagnostic message an additional check needs to be done here to test something else that would detect that the domain exists but is not a zone. Any suggestions are welcome.

**Comment by bortzmeyer** [comment]
The test is simple : query the NS RRset. If NXDOMAIN, "domain does not exist". If NODATA (NOERROR/ANSWER=0), "domain exists but is not a zone". Otherwise, "domain exists and is a zone".

If SERVFAIL or other errors, "something wrong happened". For DNSSEC-signed domains, the query should be done with CD=1 so the testing can continue.

**Comment by mtoma** [comment]
Ok, this seems perfect. I'll chenge this in the backend.

**Comment by sandoche2k** [comment]
@mtoma - i think i still have the issue because you have not yet updated the server to the latest release. 
@pawal - Assign to @mtoma 
@mtoma - this should be for release .3

**Comment by mtoma** [comment]
This one is fixed. The release is just not online yet.

----- Original Message -----

**Comment by sandoche2k** [comment]
@mtoma Can you make a release with current fixes?

**Comment by mtoma** [comment]
No, no release will be done unless it passes a set of non regression tests.

----- Original Message -----

**Comment by sandoche2k** [comment]
@mtoma  works in your bleeding edge version :-)

**Comment by sandoche2k** [comment]
@bortzmeyer Can you check with http://zonemaster.fr:5080 and respond whether you are satisfied with the result?

**Comment by bortzmeyer** [comment]
I find the messages hard to understand, specially the second one:

 Not enough data about gouv.fr was found to be able to run tests.
Nameservers for "fr" provided no NS records for tested zone. RCODE given was NOERROR.

**Comment by sandoche2k** [comment]
@bortzmeyer - Can this issue be closed?

**Comment by bortzmeyer** [comment]
OK, on the version of the Web site, the answer is correct.
